### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by jiamo** [orf/simple#50]
Flow you readme met this error. System ubunut14.10

supervisorctl start simple
Error: .ini file does not include supervisorctl section
For help, use /usr/bin/supervisorctl -h

the created  supervisord.conf like this, have no supervisorctl section

[program:simple]
 
environment=PATH="/home/ikfb/Git/blog/env/bin"
user=nobody
autostart=true
autorestart=true
killasgroup = true
redirect_stdout=true
redirect_stderr=true

**Comment by orf** [comment]
Strange, I wasn't aware that it requires a supervisorctl section and the config is meant to include one by default anyway (hence the >> to append). Does adding a blank [supervisorctl] section fix it?

**Comment by jiamo** [comment]
Got it. I just create new file and copy it. Should see more carefully.
